Repository Automattic/jetmon, pull requests merged in 2023-03, with the labels that each got.

#28 Stats: Replace hot-shots library with raw socket sends
  lib/httpcheck.js
  lib/statsd.js
  package.json
Labels: enhancement, Needs Review

#29 Stats: Track how long each round takes
  lib/jetmon.js
Labels: enhancement, Needs Review

#31 Fix: Corrected site_status var and set default val
  lib/httpcheck.js
Labels: enhancement, Needs Review

#32 Stats: Add metric buffering
  lib/httpcheck.js
  lib/jetmon.js
  lib/statsd.js
Labels: enhancement, Needs Review, Performance

#33 WPCOM API: make `last_status_change` nullable
  lib/wpcom.js
Labels: Needs Review

#34 Stats: Migrate stats to use timing instead of gauge.
  lib/jetmon.js
Labels: bug, Needs Review

#36 Stats: Add information about the queue sizes in the workers and how many active checks are running at the moment.
  lib/httpcheck.js
  lib/jetmon.js
Labels: Needs Review, Performance

#37 Workers: Push work to the worker if it's queue is not saturated enough
  lib/jetmon.js
Labels: enhancement, Needs Review, Performance

#35 Enhancement: Run the main loop every minute to allow variable intervals
  config/config-sample.json
  lib/database.js
  lib/jetmon.js
Labels: enhancement, Needs Review

#38 Migrate to Node 18
  .npmrc
  docker/Dockerfile_jetmon
Labels: Needs Review, janitorial

#42 Fix/site scanning on one minute rounds
  config/config-sample.json
  config/config.readme
  lib/database.js
  lib/jetmon.js
  lib/wpcom.js
Labels: bug, Needs Review
