Repository Automattic/jetmon, pull requests merged in 2023-06, with the labels that each got.

#40 Update: Add monitor_url to verflier messages
  lib/jetmon.js
  veriflier/headers/check_controller.h
  veriflier/headers/check_thread.h
  veriflier/source/check_controller.cpp
  veriflier/source/check_thread.cpp
Labels: enhancement

#48 Fix incorrect SPS metric calculations and flush cached child stats before recycling
  config/config-sample.json
  lib/httpcheck.js
  lib/jetmon.js
Labels: bug, Needs Review

#51 Switch HTTP_Checker to `getaddrinfo`
  src/http_checker.h
Labels: Needs Review
